# Generated by Django 2.0.3 on 2019-06-27 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190627_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 22, 50, 13, 29399)),
        ),
    ]
