# Generated by Django 2.0.3 on 2019-06-27 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190627_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
